USE [master]
GO
/****** Object:  Database [Desafio3]    Script Date: 3/6/2021 06:16:52 ******/
CREATE DATABASE [Desafio3]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Desafio2', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Desafio2.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Desafio2_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Desafio2_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [Desafio3] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Desafio3].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Desafio3] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Desafio3] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Desafio3] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Desafio3] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Desafio3] SET ARITHABORT OFF 
GO
ALTER DATABASE [Desafio3] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Desafio3] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Desafio3] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Desafio3] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Desafio3] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Desafio3] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Desafio3] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Desafio3] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Desafio3] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Desafio3] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Desafio3] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Desafio3] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Desafio3] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Desafio3] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Desafio3] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Desafio3] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Desafio3] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Desafio3] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [Desafio3] SET  MULTI_USER 
GO
ALTER DATABASE [Desafio3] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Desafio3] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Desafio3] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Desafio3] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Desafio3] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [Desafio3] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [Desafio3] SET QUERY_STORE = OFF
GO
USE [Desafio3]
GO
/****** Object:  Table [dbo].[Usuarios]    Script Date: 3/6/2021 06:16:52 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Usuarios](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [varchar](50) NOT NULL,
	[Apellido] [varchar](50) NOT NULL,
	[Email] [varchar](50) NOT NULL,
	[Password] [varchar](50) NOT NULL,
 CONSTRAINT [PK_Usuarios] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[Usuarios] ON 
GO
INSERT [dbo].[Usuarios] ([Id], [Nombre], [Apellido], [Email], [Password]) VALUES (1, N'nombre', N'modificado', N'maxi@gmail.com', N'1234')
GO
INSERT [dbo].[Usuarios] ([Id], [Nombre], [Apellido], [Email], [Password]) VALUES (2, N'Jonatan', N'Cari', N'jonatan@gmail.com', N'1234')
GO
SET IDENTITY_INSERT [dbo].[Usuarios] OFF
GO
USE [master]
GO
ALTER DATABASE [Desafio3] SET  READ_WRITE 
GO
